name: Auto Merge

on:
  pull_request:
    types: [labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'auto-merge'
    steps:
      - uses: actions/checkout@v2
      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
    run: |
      git config --global user.email "action@github.com"
      git config --global user.name "GitHub Action"
      git merge origin/${
     { github.event.pull_request.base.ref }} -m "Auto merge PR ${
     { github.event.pull_request.number }}"
     git push